import { expect, it } from 'vitest';
import beforeSplit from './fixtures/skills/before-split.json';
import { readGuide } from '../src/engine/skills';

// Captured from the original skills.ts before moving any code; never regenerated by this test.
it.each(Object.entries(beforeSplit))('read_guide preserves the exact pre-split text for %s', (id, text) => {
  expect(readGuide(id)).toBe(text);
});
