export function savePilotFixtures(root: string, fixtures: unknown[]): Promise<void>;
export function estimatePilot(fixtures: any[]): any;
export function reserveCall(ledger: any, row: any, limitMicroUsd?: number): void;
export function settleCall(ledger: any, row: any, reportedUsd: unknown, limitMicroUsd?: number): void;
export function sampleRequest(body: any, key: string, fetcher?: typeof fetch): Promise<any>;
export function readPilot(root: string): Promise<any>;
export function environmentKey(env?: Record<string, unknown>): string;
export function requestFailure(error: unknown): { failureKind: string; failurePhase: string; httpStatus: number | string; providerErrorCode: number | string; providerErrorType: number | string; reportedUsd?: number };
export function failureSummary(error: unknown): string;
export function runPilot(fixtures: any[], ledger: any, save: (ledger: any) => Promise<void>, env?: Record<string, unknown>, fetcher?: typeof fetch): Promise<any>;
